version: '3.8'
services:
  mysql:
    platform: linux/amd64
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    expose: 
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - jottNetwork
  userapi:
    build: 
      context: .
      dockerfile: ./cmd/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - jottNetwork
    
volumes:
  mysql-data:

networks:
   jottNetwork:
     driver: "bridge"

